[project]
name = "chatbot"
version = "0.1.0"
description = "chatbot with chai"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "requests>=2.32.4",
    "ruff>=0.12.1",
]
